development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:e83883b73b75ec24f095ab411a6c6ea7@hammerjaw.redistogo.com:11045/
  channel_prefix: backend_production
