development:
  database: backend_development
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  host: localhost
  port: 5432

test:
  database: backend_test
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  host: localhost
  port: 5432

production:
  url: <%= ENV['DATABASE_URL'] %>
