default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
